
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OrderCoupon` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model OrderCoupon
 * 
 */
export type OrderCouponModel = runtime.Types.Result.DefaultSelection<Prisma.$OrderCouponPayload>

export type AggregateOrderCoupon = {
  _count: OrderCouponCountAggregateOutputType | null
  _min: OrderCouponMinAggregateOutputType | null
  _max: OrderCouponMaxAggregateOutputType | null
}

export type OrderCouponMinAggregateOutputType = {
  id: string | null
  orderId: string | null
  couponId: string | null
  code: string | null
}

export type OrderCouponMaxAggregateOutputType = {
  id: string | null
  orderId: string | null
  couponId: string | null
  code: string | null
}

export type OrderCouponCountAggregateOutputType = {
  id: number
  orderId: number
  couponId: number
  code: number
  _all: number
}


export type OrderCouponMinAggregateInputType = {
  id?: true
  orderId?: true
  couponId?: true
  code?: true
}

export type OrderCouponMaxAggregateInputType = {
  id?: true
  orderId?: true
  couponId?: true
  code?: true
}

export type OrderCouponCountAggregateInputType = {
  id?: true
  orderId?: true
  couponId?: true
  code?: true
  _all?: true
}

export type OrderCouponAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrderCoupon to aggregate.
   */
  where?: Prisma.OrderCouponWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderCoupons to fetch.
   */
  orderBy?: Prisma.OrderCouponOrderByWithRelationInput | Prisma.OrderCouponOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OrderCouponWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderCoupons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderCoupons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OrderCoupons
  **/
  _count?: true | OrderCouponCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrderCouponMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrderCouponMaxAggregateInputType
}

export type GetOrderCouponAggregateType<T extends OrderCouponAggregateArgs> = {
      [P in keyof T & keyof AggregateOrderCoupon]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrderCoupon[P]>
    : Prisma.GetScalarType<T[P], AggregateOrderCoupon[P]>
}




export type OrderCouponGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderCouponWhereInput
  orderBy?: Prisma.OrderCouponOrderByWithAggregationInput | Prisma.OrderCouponOrderByWithAggregationInput[]
  by: Prisma.OrderCouponScalarFieldEnum[] | Prisma.OrderCouponScalarFieldEnum
  having?: Prisma.OrderCouponScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrderCouponCountAggregateInputType | true
  _min?: OrderCouponMinAggregateInputType
  _max?: OrderCouponMaxAggregateInputType
}

export type OrderCouponGroupByOutputType = {
  id: string
  orderId: string
  couponId: string
  code: string
  _count: OrderCouponCountAggregateOutputType | null
  _min: OrderCouponMinAggregateOutputType | null
  _max: OrderCouponMaxAggregateOutputType | null
}

export type GetOrderCouponGroupByPayload<T extends OrderCouponGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrderCouponGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrderCouponGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrderCouponGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrderCouponGroupByOutputType[P]>
      }
    >
  >



export type OrderCouponWhereInput = {
  AND?: Prisma.OrderCouponWhereInput | Prisma.OrderCouponWhereInput[]
  OR?: Prisma.OrderCouponWhereInput[]
  NOT?: Prisma.OrderCouponWhereInput | Prisma.OrderCouponWhereInput[]
  id?: Prisma.StringFilter<"OrderCoupon"> | string
  orderId?: Prisma.StringFilter<"OrderCoupon"> | string
  couponId?: Prisma.StringFilter<"OrderCoupon"> | string
  code?: Prisma.StringFilter<"OrderCoupon"> | string
  order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
  coupon?: Prisma.XOR<Prisma.CouponScalarRelationFilter, Prisma.CouponWhereInput>
}

export type OrderCouponOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  couponId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  order?: Prisma.OrderOrderByWithRelationInput
  coupon?: Prisma.CouponOrderByWithRelationInput
}

export type OrderCouponWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  orderId_couponId?: Prisma.OrderCouponOrderIdCouponIdCompoundUniqueInput
  AND?: Prisma.OrderCouponWhereInput | Prisma.OrderCouponWhereInput[]
  OR?: Prisma.OrderCouponWhereInput[]
  NOT?: Prisma.OrderCouponWhereInput | Prisma.OrderCouponWhereInput[]
  orderId?: Prisma.StringFilter<"OrderCoupon"> | string
  couponId?: Prisma.StringFilter<"OrderCoupon"> | string
  code?: Prisma.StringFilter<"OrderCoupon"> | string
  order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
  coupon?: Prisma.XOR<Prisma.CouponScalarRelationFilter, Prisma.CouponWhereInput>
}, "id" | "orderId_couponId">

export type OrderCouponOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  couponId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  _count?: Prisma.OrderCouponCountOrderByAggregateInput
  _max?: Prisma.OrderCouponMaxOrderByAggregateInput
  _min?: Prisma.OrderCouponMinOrderByAggregateInput
}

export type OrderCouponScalarWhereWithAggregatesInput = {
  AND?: Prisma.OrderCouponScalarWhereWithAggregatesInput | Prisma.OrderCouponScalarWhereWithAggregatesInput[]
  OR?: Prisma.OrderCouponScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OrderCouponScalarWhereWithAggregatesInput | Prisma.OrderCouponScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OrderCoupon"> | string
  orderId?: Prisma.StringWithAggregatesFilter<"OrderCoupon"> | string
  couponId?: Prisma.StringWithAggregatesFilter<"OrderCoupon"> | string
  code?: Prisma.StringWithAggregatesFilter<"OrderCoupon"> | string
}

export type OrderCouponCreateInput = {
  id?: string
  code: string
  order: Prisma.OrderCreateNestedOneWithoutOrderCouponInput
  coupon: Prisma.CouponCreateNestedOneWithoutOrderCouponInput
}

export type OrderCouponUncheckedCreateInput = {
  id?: string
  orderId: string
  couponId: string
  code: string
}

export type OrderCouponUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.OrderUpdateOneRequiredWithoutOrderCouponNestedInput
  coupon?: Prisma.CouponUpdateOneRequiredWithoutOrderCouponNestedInput
}

export type OrderCouponUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  couponId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
}

export type OrderCouponCreateManyInput = {
  id?: string
  orderId: string
  couponId: string
  code: string
}

export type OrderCouponUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
}

export type OrderCouponUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  couponId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
}

export type OrderCouponListRelationFilter = {
  every?: Prisma.OrderCouponWhereInput
  some?: Prisma.OrderCouponWhereInput
  none?: Prisma.OrderCouponWhereInput
}

export type OrderCouponOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OrderCouponOrderIdCouponIdCompoundUniqueInput = {
  orderId: string
  couponId: string
}

export type OrderCouponCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  couponId?: Prisma.SortOrder
  code?: Prisma.SortOrder
}

export type OrderCouponMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  couponId?: Prisma.SortOrder
  code?: Prisma.SortOrder
}

export type OrderCouponMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  couponId?: Prisma.SortOrder
  code?: Prisma.SortOrder
}

export type OrderCouponCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.OrderCouponCreateWithoutOrderInput, Prisma.OrderCouponUncheckedCreateWithoutOrderInput> | Prisma.OrderCouponCreateWithoutOrderInput[] | Prisma.OrderCouponUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.OrderCouponCreateOrConnectWithoutOrderInput | Prisma.OrderCouponCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.OrderCouponCreateManyOrderInputEnvelope
  connect?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
}

export type OrderCouponUncheckedCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.OrderCouponCreateWithoutOrderInput, Prisma.OrderCouponUncheckedCreateWithoutOrderInput> | Prisma.OrderCouponCreateWithoutOrderInput[] | Prisma.OrderCouponUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.OrderCouponCreateOrConnectWithoutOrderInput | Prisma.OrderCouponCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.OrderCouponCreateManyOrderInputEnvelope
  connect?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
}

export type OrderCouponUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCouponCreateWithoutOrderInput, Prisma.OrderCouponUncheckedCreateWithoutOrderInput> | Prisma.OrderCouponCreateWithoutOrderInput[] | Prisma.OrderCouponUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.OrderCouponCreateOrConnectWithoutOrderInput | Prisma.OrderCouponCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.OrderCouponUpsertWithWhereUniqueWithoutOrderInput | Prisma.OrderCouponUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.OrderCouponCreateManyOrderInputEnvelope
  set?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  disconnect?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  delete?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  connect?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  update?: Prisma.OrderCouponUpdateWithWhereUniqueWithoutOrderInput | Prisma.OrderCouponUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.OrderCouponUpdateManyWithWhereWithoutOrderInput | Prisma.OrderCouponUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.OrderCouponScalarWhereInput | Prisma.OrderCouponScalarWhereInput[]
}

export type OrderCouponUncheckedUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCouponCreateWithoutOrderInput, Prisma.OrderCouponUncheckedCreateWithoutOrderInput> | Prisma.OrderCouponCreateWithoutOrderInput[] | Prisma.OrderCouponUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.OrderCouponCreateOrConnectWithoutOrderInput | Prisma.OrderCouponCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.OrderCouponUpsertWithWhereUniqueWithoutOrderInput | Prisma.OrderCouponUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.OrderCouponCreateManyOrderInputEnvelope
  set?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  disconnect?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  delete?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  connect?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  update?: Prisma.OrderCouponUpdateWithWhereUniqueWithoutOrderInput | Prisma.OrderCouponUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.OrderCouponUpdateManyWithWhereWithoutOrderInput | Prisma.OrderCouponUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.OrderCouponScalarWhereInput | Prisma.OrderCouponScalarWhereInput[]
}

export type OrderCouponCreateNestedManyWithoutCouponInput = {
  create?: Prisma.XOR<Prisma.OrderCouponCreateWithoutCouponInput, Prisma.OrderCouponUncheckedCreateWithoutCouponInput> | Prisma.OrderCouponCreateWithoutCouponInput[] | Prisma.OrderCouponUncheckedCreateWithoutCouponInput[]
  connectOrCreate?: Prisma.OrderCouponCreateOrConnectWithoutCouponInput | Prisma.OrderCouponCreateOrConnectWithoutCouponInput[]
  createMany?: Prisma.OrderCouponCreateManyCouponInputEnvelope
  connect?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
}

export type OrderCouponUncheckedCreateNestedManyWithoutCouponInput = {
  create?: Prisma.XOR<Prisma.OrderCouponCreateWithoutCouponInput, Prisma.OrderCouponUncheckedCreateWithoutCouponInput> | Prisma.OrderCouponCreateWithoutCouponInput[] | Prisma.OrderCouponUncheckedCreateWithoutCouponInput[]
  connectOrCreate?: Prisma.OrderCouponCreateOrConnectWithoutCouponInput | Prisma.OrderCouponCreateOrConnectWithoutCouponInput[]
  createMany?: Prisma.OrderCouponCreateManyCouponInputEnvelope
  connect?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
}

export type OrderCouponUpdateManyWithoutCouponNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCouponCreateWithoutCouponInput, Prisma.OrderCouponUncheckedCreateWithoutCouponInput> | Prisma.OrderCouponCreateWithoutCouponInput[] | Prisma.OrderCouponUncheckedCreateWithoutCouponInput[]
  connectOrCreate?: Prisma.OrderCouponCreateOrConnectWithoutCouponInput | Prisma.OrderCouponCreateOrConnectWithoutCouponInput[]
  upsert?: Prisma.OrderCouponUpsertWithWhereUniqueWithoutCouponInput | Prisma.OrderCouponUpsertWithWhereUniqueWithoutCouponInput[]
  createMany?: Prisma.OrderCouponCreateManyCouponInputEnvelope
  set?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  disconnect?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  delete?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  connect?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  update?: Prisma.OrderCouponUpdateWithWhereUniqueWithoutCouponInput | Prisma.OrderCouponUpdateWithWhereUniqueWithoutCouponInput[]
  updateMany?: Prisma.OrderCouponUpdateManyWithWhereWithoutCouponInput | Prisma.OrderCouponUpdateManyWithWhereWithoutCouponInput[]
  deleteMany?: Prisma.OrderCouponScalarWhereInput | Prisma.OrderCouponScalarWhereInput[]
}

export type OrderCouponUncheckedUpdateManyWithoutCouponNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCouponCreateWithoutCouponInput, Prisma.OrderCouponUncheckedCreateWithoutCouponInput> | Prisma.OrderCouponCreateWithoutCouponInput[] | Prisma.OrderCouponUncheckedCreateWithoutCouponInput[]
  connectOrCreate?: Prisma.OrderCouponCreateOrConnectWithoutCouponInput | Prisma.OrderCouponCreateOrConnectWithoutCouponInput[]
  upsert?: Prisma.OrderCouponUpsertWithWhereUniqueWithoutCouponInput | Prisma.OrderCouponUpsertWithWhereUniqueWithoutCouponInput[]
  createMany?: Prisma.OrderCouponCreateManyCouponInputEnvelope
  set?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  disconnect?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  delete?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  connect?: Prisma.OrderCouponWhereUniqueInput | Prisma.OrderCouponWhereUniqueInput[]
  update?: Prisma.OrderCouponUpdateWithWhereUniqueWithoutCouponInput | Prisma.OrderCouponUpdateWithWhereUniqueWithoutCouponInput[]
  updateMany?: Prisma.OrderCouponUpdateManyWithWhereWithoutCouponInput | Prisma.OrderCouponUpdateManyWithWhereWithoutCouponInput[]
  deleteMany?: Prisma.OrderCouponScalarWhereInput | Prisma.OrderCouponScalarWhereInput[]
}

export type OrderCouponCreateWithoutOrderInput = {
  id?: string
  code: string
  coupon: Prisma.CouponCreateNestedOneWithoutOrderCouponInput
}

export type OrderCouponUncheckedCreateWithoutOrderInput = {
  id?: string
  couponId: string
  code: string
}

export type OrderCouponCreateOrConnectWithoutOrderInput = {
  where: Prisma.OrderCouponWhereUniqueInput
  create: Prisma.XOR<Prisma.OrderCouponCreateWithoutOrderInput, Prisma.OrderCouponUncheckedCreateWithoutOrderInput>
}

export type OrderCouponCreateManyOrderInputEnvelope = {
  data: Prisma.OrderCouponCreateManyOrderInput | Prisma.OrderCouponCreateManyOrderInput[]
  skipDuplicates?: boolean
}

export type OrderCouponUpsertWithWhereUniqueWithoutOrderInput = {
  where: Prisma.OrderCouponWhereUniqueInput
  update: Prisma.XOR<Prisma.OrderCouponUpdateWithoutOrderInput, Prisma.OrderCouponUncheckedUpdateWithoutOrderInput>
  create: Prisma.XOR<Prisma.OrderCouponCreateWithoutOrderInput, Prisma.OrderCouponUncheckedCreateWithoutOrderInput>
}

export type OrderCouponUpdateWithWhereUniqueWithoutOrderInput = {
  where: Prisma.OrderCouponWhereUniqueInput
  data: Prisma.XOR<Prisma.OrderCouponUpdateWithoutOrderInput, Prisma.OrderCouponUncheckedUpdateWithoutOrderInput>
}

export type OrderCouponUpdateManyWithWhereWithoutOrderInput = {
  where: Prisma.OrderCouponScalarWhereInput
  data: Prisma.XOR<Prisma.OrderCouponUpdateManyMutationInput, Prisma.OrderCouponUncheckedUpdateManyWithoutOrderInput>
}

export type OrderCouponScalarWhereInput = {
  AND?: Prisma.OrderCouponScalarWhereInput | Prisma.OrderCouponScalarWhereInput[]
  OR?: Prisma.OrderCouponScalarWhereInput[]
  NOT?: Prisma.OrderCouponScalarWhereInput | Prisma.OrderCouponScalarWhereInput[]
  id?: Prisma.StringFilter<"OrderCoupon"> | string
  orderId?: Prisma.StringFilter<"OrderCoupon"> | string
  couponId?: Prisma.StringFilter<"OrderCoupon"> | string
  code?: Prisma.StringFilter<"OrderCoupon"> | string
}

export type OrderCouponCreateWithoutCouponInput = {
  id?: string
  code: string
  order: Prisma.OrderCreateNestedOneWithoutOrderCouponInput
}

export type OrderCouponUncheckedCreateWithoutCouponInput = {
  id?: string
  orderId: string
  code: string
}

export type OrderCouponCreateOrConnectWithoutCouponInput = {
  where: Prisma.OrderCouponWhereUniqueInput
  create: Prisma.XOR<Prisma.OrderCouponCreateWithoutCouponInput, Prisma.OrderCouponUncheckedCreateWithoutCouponInput>
}

export type OrderCouponCreateManyCouponInputEnvelope = {
  data: Prisma.OrderCouponCreateManyCouponInput | Prisma.OrderCouponCreateManyCouponInput[]
  skipDuplicates?: boolean
}

export type OrderCouponUpsertWithWhereUniqueWithoutCouponInput = {
  where: Prisma.OrderCouponWhereUniqueInput
  update: Prisma.XOR<Prisma.OrderCouponUpdateWithoutCouponInput, Prisma.OrderCouponUncheckedUpdateWithoutCouponInput>
  create: Prisma.XOR<Prisma.OrderCouponCreateWithoutCouponInput, Prisma.OrderCouponUncheckedCreateWithoutCouponInput>
}

export type OrderCouponUpdateWithWhereUniqueWithoutCouponInput = {
  where: Prisma.OrderCouponWhereUniqueInput
  data: Prisma.XOR<Prisma.OrderCouponUpdateWithoutCouponInput, Prisma.OrderCouponUncheckedUpdateWithoutCouponInput>
}

export type OrderCouponUpdateManyWithWhereWithoutCouponInput = {
  where: Prisma.OrderCouponScalarWhereInput
  data: Prisma.XOR<Prisma.OrderCouponUpdateManyMutationInput, Prisma.OrderCouponUncheckedUpdateManyWithoutCouponInput>
}

export type OrderCouponCreateManyOrderInput = {
  id?: string
  couponId: string
  code: string
}

export type OrderCouponUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  coupon?: Prisma.CouponUpdateOneRequiredWithoutOrderCouponNestedInput
}

export type OrderCouponUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  couponId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
}

export type OrderCouponUncheckedUpdateManyWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  couponId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
}

export type OrderCouponCreateManyCouponInput = {
  id?: string
  orderId: string
  code: string
}

export type OrderCouponUpdateWithoutCouponInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.OrderUpdateOneRequiredWithoutOrderCouponNestedInput
}

export type OrderCouponUncheckedUpdateWithoutCouponInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
}

export type OrderCouponUncheckedUpdateManyWithoutCouponInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
}



export type OrderCouponSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  couponId?: boolean
  code?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  coupon?: boolean | Prisma.CouponDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orderCoupon"]>

export type OrderCouponSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  couponId?: boolean
  code?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  coupon?: boolean | Prisma.CouponDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orderCoupon"]>

export type OrderCouponSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  couponId?: boolean
  code?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  coupon?: boolean | Prisma.CouponDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orderCoupon"]>

export type OrderCouponSelectScalar = {
  id?: boolean
  orderId?: boolean
  couponId?: boolean
  code?: boolean
}

export type OrderCouponOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "orderId" | "couponId" | "code", ExtArgs["result"]["orderCoupon"]>
export type OrderCouponInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  coupon?: boolean | Prisma.CouponDefaultArgs<ExtArgs>
}
export type OrderCouponIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  coupon?: boolean | Prisma.CouponDefaultArgs<ExtArgs>
}
export type OrderCouponIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  coupon?: boolean | Prisma.CouponDefaultArgs<ExtArgs>
}

export type $OrderCouponPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OrderCoupon"
  objects: {
    order: Prisma.$OrderPayload<ExtArgs>
    coupon: Prisma.$CouponPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    orderId: string
    couponId: string
    code: string
  }, ExtArgs["result"]["orderCoupon"]>
  composites: {}
}

export type OrderCouponGetPayload<S extends boolean | null | undefined | OrderCouponDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OrderCouponPayload, S>

export type OrderCouponCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OrderCouponFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OrderCouponCountAggregateInputType | true
  }

export interface OrderCouponDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OrderCoupon'], meta: { name: 'OrderCoupon' } }
  /**
   * Find zero or one OrderCoupon that matches the filter.
   * @param {OrderCouponFindUniqueArgs} args - Arguments to find a OrderCoupon
   * @example
   * // Get one OrderCoupon
   * const orderCoupon = await prisma.orderCoupon.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrderCouponFindUniqueArgs>(args: Prisma.SelectSubset<T, OrderCouponFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OrderCouponClient<runtime.Types.Result.GetResult<Prisma.$OrderCouponPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OrderCoupon that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrderCouponFindUniqueOrThrowArgs} args - Arguments to find a OrderCoupon
   * @example
   * // Get one OrderCoupon
   * const orderCoupon = await prisma.orderCoupon.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrderCouponFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OrderCouponFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrderCouponClient<runtime.Types.Result.GetResult<Prisma.$OrderCouponPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrderCoupon that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderCouponFindFirstArgs} args - Arguments to find a OrderCoupon
   * @example
   * // Get one OrderCoupon
   * const orderCoupon = await prisma.orderCoupon.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrderCouponFindFirstArgs>(args?: Prisma.SelectSubset<T, OrderCouponFindFirstArgs<ExtArgs>>): Prisma.Prisma__OrderCouponClient<runtime.Types.Result.GetResult<Prisma.$OrderCouponPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrderCoupon that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderCouponFindFirstOrThrowArgs} args - Arguments to find a OrderCoupon
   * @example
   * // Get one OrderCoupon
   * const orderCoupon = await prisma.orderCoupon.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrderCouponFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OrderCouponFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrderCouponClient<runtime.Types.Result.GetResult<Prisma.$OrderCouponPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OrderCoupons that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderCouponFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OrderCoupons
   * const orderCoupons = await prisma.orderCoupon.findMany()
   * 
   * // Get first 10 OrderCoupons
   * const orderCoupons = await prisma.orderCoupon.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orderCouponWithIdOnly = await prisma.orderCoupon.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OrderCouponFindManyArgs>(args?: Prisma.SelectSubset<T, OrderCouponFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderCouponPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OrderCoupon.
   * @param {OrderCouponCreateArgs} args - Arguments to create a OrderCoupon.
   * @example
   * // Create one OrderCoupon
   * const OrderCoupon = await prisma.orderCoupon.create({
   *   data: {
   *     // ... data to create a OrderCoupon
   *   }
   * })
   * 
   */
  create<T extends OrderCouponCreateArgs>(args: Prisma.SelectSubset<T, OrderCouponCreateArgs<ExtArgs>>): Prisma.Prisma__OrderCouponClient<runtime.Types.Result.GetResult<Prisma.$OrderCouponPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OrderCoupons.
   * @param {OrderCouponCreateManyArgs} args - Arguments to create many OrderCoupons.
   * @example
   * // Create many OrderCoupons
   * const orderCoupon = await prisma.orderCoupon.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OrderCouponCreateManyArgs>(args?: Prisma.SelectSubset<T, OrderCouponCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OrderCoupons and returns the data saved in the database.
   * @param {OrderCouponCreateManyAndReturnArgs} args - Arguments to create many OrderCoupons.
   * @example
   * // Create many OrderCoupons
   * const orderCoupon = await prisma.orderCoupon.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OrderCoupons and only return the `id`
   * const orderCouponWithIdOnly = await prisma.orderCoupon.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OrderCouponCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OrderCouponCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderCouponPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OrderCoupon.
   * @param {OrderCouponDeleteArgs} args - Arguments to delete one OrderCoupon.
   * @example
   * // Delete one OrderCoupon
   * const OrderCoupon = await prisma.orderCoupon.delete({
   *   where: {
   *     // ... filter to delete one OrderCoupon
   *   }
   * })
   * 
   */
  delete<T extends OrderCouponDeleteArgs>(args: Prisma.SelectSubset<T, OrderCouponDeleteArgs<ExtArgs>>): Prisma.Prisma__OrderCouponClient<runtime.Types.Result.GetResult<Prisma.$OrderCouponPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OrderCoupon.
   * @param {OrderCouponUpdateArgs} args - Arguments to update one OrderCoupon.
   * @example
   * // Update one OrderCoupon
   * const orderCoupon = await prisma.orderCoupon.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OrderCouponUpdateArgs>(args: Prisma.SelectSubset<T, OrderCouponUpdateArgs<ExtArgs>>): Prisma.Prisma__OrderCouponClient<runtime.Types.Result.GetResult<Prisma.$OrderCouponPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OrderCoupons.
   * @param {OrderCouponDeleteManyArgs} args - Arguments to filter OrderCoupons to delete.
   * @example
   * // Delete a few OrderCoupons
   * const { count } = await prisma.orderCoupon.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OrderCouponDeleteManyArgs>(args?: Prisma.SelectSubset<T, OrderCouponDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrderCoupons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderCouponUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OrderCoupons
   * const orderCoupon = await prisma.orderCoupon.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OrderCouponUpdateManyArgs>(args: Prisma.SelectSubset<T, OrderCouponUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrderCoupons and returns the data updated in the database.
   * @param {OrderCouponUpdateManyAndReturnArgs} args - Arguments to update many OrderCoupons.
   * @example
   * // Update many OrderCoupons
   * const orderCoupon = await prisma.orderCoupon.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OrderCoupons and only return the `id`
   * const orderCouponWithIdOnly = await prisma.orderCoupon.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OrderCouponUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OrderCouponUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderCouponPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OrderCoupon.
   * @param {OrderCouponUpsertArgs} args - Arguments to update or create a OrderCoupon.
   * @example
   * // Update or create a OrderCoupon
   * const orderCoupon = await prisma.orderCoupon.upsert({
   *   create: {
   *     // ... data to create a OrderCoupon
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OrderCoupon we want to update
   *   }
   * })
   */
  upsert<T extends OrderCouponUpsertArgs>(args: Prisma.SelectSubset<T, OrderCouponUpsertArgs<ExtArgs>>): Prisma.Prisma__OrderCouponClient<runtime.Types.Result.GetResult<Prisma.$OrderCouponPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OrderCoupons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderCouponCountArgs} args - Arguments to filter OrderCoupons to count.
   * @example
   * // Count the number of OrderCoupons
   * const count = await prisma.orderCoupon.count({
   *   where: {
   *     // ... the filter for the OrderCoupons we want to count
   *   }
   * })
  **/
  count<T extends OrderCouponCountArgs>(
    args?: Prisma.Subset<T, OrderCouponCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrderCouponCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OrderCoupon.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderCouponAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrderCouponAggregateArgs>(args: Prisma.Subset<T, OrderCouponAggregateArgs>): Prisma.PrismaPromise<GetOrderCouponAggregateType<T>>

  /**
   * Group by OrderCoupon.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderCouponGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OrderCouponGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrderCouponGroupByArgs['orderBy'] }
      : { orderBy?: OrderCouponGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OrderCouponGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrderCouponGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OrderCoupon model
 */
readonly fields: OrderCouponFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OrderCoupon.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrderCouponClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  order<T extends Prisma.OrderDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrderDefaultArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  coupon<T extends Prisma.CouponDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CouponDefaultArgs<ExtArgs>>): Prisma.Prisma__CouponClient<runtime.Types.Result.GetResult<Prisma.$CouponPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OrderCoupon model
 */
export interface OrderCouponFieldRefs {
  readonly id: Prisma.FieldRef<"OrderCoupon", 'String'>
  readonly orderId: Prisma.FieldRef<"OrderCoupon", 'String'>
  readonly couponId: Prisma.FieldRef<"OrderCoupon", 'String'>
  readonly code: Prisma.FieldRef<"OrderCoupon", 'String'>
}
    

// Custom InputTypes
/**
 * OrderCoupon findUnique
 */
export type OrderCouponFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderCoupon
   */
  select?: Prisma.OrderCouponSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderCoupon
   */
  omit?: Prisma.OrderCouponOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderCouponInclude<ExtArgs> | null
  /**
   * Filter, which OrderCoupon to fetch.
   */
  where: Prisma.OrderCouponWhereUniqueInput
}

/**
 * OrderCoupon findUniqueOrThrow
 */
export type OrderCouponFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderCoupon
   */
  select?: Prisma.OrderCouponSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderCoupon
   */
  omit?: Prisma.OrderCouponOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderCouponInclude<ExtArgs> | null
  /**
   * Filter, which OrderCoupon to fetch.
   */
  where: Prisma.OrderCouponWhereUniqueInput
}

/**
 * OrderCoupon findFirst
 */
export type OrderCouponFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderCoupon
   */
  select?: Prisma.OrderCouponSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderCoupon
   */
  omit?: Prisma.OrderCouponOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderCouponInclude<ExtArgs> | null
  /**
   * Filter, which OrderCoupon to fetch.
   */
  where?: Prisma.OrderCouponWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderCoupons to fetch.
   */
  orderBy?: Prisma.OrderCouponOrderByWithRelationInput | Prisma.OrderCouponOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrderCoupons.
   */
  cursor?: Prisma.OrderCouponWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderCoupons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderCoupons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrderCoupons.
   */
  distinct?: Prisma.OrderCouponScalarFieldEnum | Prisma.OrderCouponScalarFieldEnum[]
}

/**
 * OrderCoupon findFirstOrThrow
 */
export type OrderCouponFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderCoupon
   */
  select?: Prisma.OrderCouponSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderCoupon
   */
  omit?: Prisma.OrderCouponOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderCouponInclude<ExtArgs> | null
  /**
   * Filter, which OrderCoupon to fetch.
   */
  where?: Prisma.OrderCouponWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderCoupons to fetch.
   */
  orderBy?: Prisma.OrderCouponOrderByWithRelationInput | Prisma.OrderCouponOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrderCoupons.
   */
  cursor?: Prisma.OrderCouponWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderCoupons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderCoupons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrderCoupons.
   */
  distinct?: Prisma.OrderCouponScalarFieldEnum | Prisma.OrderCouponScalarFieldEnum[]
}

/**
 * OrderCoupon findMany
 */
export type OrderCouponFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderCoupon
   */
  select?: Prisma.OrderCouponSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderCoupon
   */
  omit?: Prisma.OrderCouponOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderCouponInclude<ExtArgs> | null
  /**
   * Filter, which OrderCoupons to fetch.
   */
  where?: Prisma.OrderCouponWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderCoupons to fetch.
   */
  orderBy?: Prisma.OrderCouponOrderByWithRelationInput | Prisma.OrderCouponOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OrderCoupons.
   */
  cursor?: Prisma.OrderCouponWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderCoupons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderCoupons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrderCoupons.
   */
  distinct?: Prisma.OrderCouponScalarFieldEnum | Prisma.OrderCouponScalarFieldEnum[]
}

/**
 * OrderCoupon create
 */
export type OrderCouponCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderCoupon
   */
  select?: Prisma.OrderCouponSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderCoupon
   */
  omit?: Prisma.OrderCouponOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderCouponInclude<ExtArgs> | null
  /**
   * The data needed to create a OrderCoupon.
   */
  data: Prisma.XOR<Prisma.OrderCouponCreateInput, Prisma.OrderCouponUncheckedCreateInput>
}

/**
 * OrderCoupon createMany
 */
export type OrderCouponCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OrderCoupons.
   */
  data: Prisma.OrderCouponCreateManyInput | Prisma.OrderCouponCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OrderCoupon createManyAndReturn
 */
export type OrderCouponCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderCoupon
   */
  select?: Prisma.OrderCouponSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrderCoupon
   */
  omit?: Prisma.OrderCouponOmit<ExtArgs> | null
  /**
   * The data used to create many OrderCoupons.
   */
  data: Prisma.OrderCouponCreateManyInput | Prisma.OrderCouponCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderCouponIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OrderCoupon update
 */
export type OrderCouponUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderCoupon
   */
  select?: Prisma.OrderCouponSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderCoupon
   */
  omit?: Prisma.OrderCouponOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderCouponInclude<ExtArgs> | null
  /**
   * The data needed to update a OrderCoupon.
   */
  data: Prisma.XOR<Prisma.OrderCouponUpdateInput, Prisma.OrderCouponUncheckedUpdateInput>
  /**
   * Choose, which OrderCoupon to update.
   */
  where: Prisma.OrderCouponWhereUniqueInput
}

/**
 * OrderCoupon updateMany
 */
export type OrderCouponUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OrderCoupons.
   */
  data: Prisma.XOR<Prisma.OrderCouponUpdateManyMutationInput, Prisma.OrderCouponUncheckedUpdateManyInput>
  /**
   * Filter which OrderCoupons to update
   */
  where?: Prisma.OrderCouponWhereInput
  /**
   * Limit how many OrderCoupons to update.
   */
  limit?: number
}

/**
 * OrderCoupon updateManyAndReturn
 */
export type OrderCouponUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderCoupon
   */
  select?: Prisma.OrderCouponSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrderCoupon
   */
  omit?: Prisma.OrderCouponOmit<ExtArgs> | null
  /**
   * The data used to update OrderCoupons.
   */
  data: Prisma.XOR<Prisma.OrderCouponUpdateManyMutationInput, Prisma.OrderCouponUncheckedUpdateManyInput>
  /**
   * Filter which OrderCoupons to update
   */
  where?: Prisma.OrderCouponWhereInput
  /**
   * Limit how many OrderCoupons to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderCouponIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OrderCoupon upsert
 */
export type OrderCouponUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderCoupon
   */
  select?: Prisma.OrderCouponSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderCoupon
   */
  omit?: Prisma.OrderCouponOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderCouponInclude<ExtArgs> | null
  /**
   * The filter to search for the OrderCoupon to update in case it exists.
   */
  where: Prisma.OrderCouponWhereUniqueInput
  /**
   * In case the OrderCoupon found by the `where` argument doesn't exist, create a new OrderCoupon with this data.
   */
  create: Prisma.XOR<Prisma.OrderCouponCreateInput, Prisma.OrderCouponUncheckedCreateInput>
  /**
   * In case the OrderCoupon was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OrderCouponUpdateInput, Prisma.OrderCouponUncheckedUpdateInput>
}

/**
 * OrderCoupon delete
 */
export type OrderCouponDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderCoupon
   */
  select?: Prisma.OrderCouponSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderCoupon
   */
  omit?: Prisma.OrderCouponOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderCouponInclude<ExtArgs> | null
  /**
   * Filter which OrderCoupon to delete.
   */
  where: Prisma.OrderCouponWhereUniqueInput
}

/**
 * OrderCoupon deleteMany
 */
export type OrderCouponDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrderCoupons to delete
   */
  where?: Prisma.OrderCouponWhereInput
  /**
   * Limit how many OrderCoupons to delete.
   */
  limit?: number
}

/**
 * OrderCoupon without action
 */
export type OrderCouponDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderCoupon
   */
  select?: Prisma.OrderCouponSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderCoupon
   */
  omit?: Prisma.OrderCouponOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderCouponInclude<ExtArgs> | null
}
