
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ROLE = {
  ADMIN: 'ADMIN',
  WORKER: 'WORKER',
  CLIENT: 'CLIENT'
} as const

export type ROLE = (typeof ROLE)[keyof typeof ROLE]


export const ORDER_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  EXPIRED: 'EXPIRED'
} as const

export type ORDER_STATUS = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS]


export const PROMOTION_TYPE = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED: 'FIXED'
} as const

export type PROMOTION_TYPE = (typeof PROMOTION_TYPE)[keyof typeof PROMOTION_TYPE]


export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
} as const

export type PAYMENT_STATUS = (typeof PAYMENT_STATUS)[keyof typeof PAYMENT_STATUS]


export const REFUND_STATUS = {
  PENDING: 'PENDING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED'
} as const

export type REFUND_STATUS = (typeof REFUND_STATUS)[keyof typeof REFUND_STATUS]
